<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Accounting.Core.Business\Accounting.Core.Business.csproj" />
        <ProjectReference Include="..\Accounting.Core.Domain\Accounting.Core.Domain.csproj" />
        <ProjectReference Include="..\..\Shared\Accounting.Shared\Accounting.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Seeds\Data\*.json" />
    </ItemGroup>

   

</Project>